In [1]:
import pandas as pd

In [2]:
movie = pd.read_csv('//Users//vishnuprakash//Desktop//CodSoft2//IMDB.csv', encoding='latin1')
movie

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,(2021),90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,(2010),105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali
...,...,...,...,...,...,...,...,...,...,...
15504,Zulm Ko Jala Doonga,(1988),NaN,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand
15505,Zulmi,(1999),129 min,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15506,Zulmi Raj,(2005),NaN,Action,NaN,NaN,Kiran Thej,Sangeeta Tiwari,NaN,NaN
15507,Zulmi Shikari,(1988),NaN,Action,NaN,NaN,NaN,NaN,NaN,NaN
15508,Zulm-O-Sitam,(1998),130 min,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [3]:
df = movie.dropna(subset=['Year','Duration','Genre','Rating','Votes','Director','Actor 1','Actor 2','Actor 3'])
df

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
5,...Aur Pyaar Ho Gaya,(1997),147 min,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,...Yahaan,(2005),142 min,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
8,?: A Question Mark,(2012),82 min,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia
...,...,...,...,...,...,...,...,...,...,...
15493,Zubaan,(2015),115 min,Drama,6.1,408,Mozez Singh,Vicky Kaushal,Sarah Jane Dias,Raaghavv Chanana
15494,Zubeidaa,(2001),153 min,"Biography, Drama, History",6.2,"1,496",Shyam Benegal,Karisma Kapoor,Rekha,Manoj Bajpayee
15503,Zulm Ki Zanjeer,(1989),125 min,"Action, Crime, Drama",5.8,44,S.P. Muthuraman,Chiranjeevi,Jayamalini,Rajinikanth
15505,Zulmi,(1999),129 min,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15508,Zulm-O-Sitam,(1998),130 min,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
for col in ['Genre','Director','Actor 1','Actor 2','Actor 3']:
    df.loc[:, col] = LabelEncoder().fit_transform(df[col])

In [6]:
df.loc[:, 'Duration'] = df['Duration'].astype(str).str.replace(' min', '').astype(float)

In [7]:
df.loc[:, 'Votes'] = df['Votes'].astype(str).str.replace(',', '').astype(int)

In [8]:
df.loc[:, 'Year'] = df['Year'].astype(str).str.extract(r'(\d{4})')[0].astype(int)

In [9]:
x = df.drop(['Name','Rating'],axis=1)
x

       Year Duration Genre Votes Director Actor 1 Actor 2 Actor 3
1      2019    109.0   229     8      629    1352    2272     319
3      2019    110.0   184    35     1335    1198     719    2148
5      1997    147.0   157   827     1530     378      75    2045
6      2005    142.0   289  1086     2044     692    1112    2524
8      2012     82.0   320   326      135    1934    1175    1013
...     ...      ...   ...   ...      ...     ...     ...     ...
15493  2015    115.0   229   408     1223    1861    1801    1615
15494  2001    153.0   133  1496     2059     763    1619    1184
15503  1989    125.0    28    44     1793     406     754    1685
15505  1999    129.0    38   655     1025     112    2164     314
15508  1998    130.0    38    20      895     468     753     303

[5659 rows x 8 columns]

In [10]:
y = df.Rating
y

1        7.0
3        4.4
5        4.7
6        7.4
8        5.6
        ...
15493    6.1
15494    6.2
15503    5.8
15505    4.5
15508    6.2
Name: Rating, Length: 5659, dtype: float64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
model = LinearRegression()

In [15]:

model.fit(x_train,y_train)

LinearRegression()

In [16]:
model.predict(x_test)

array([5.94568471, 5.78597402, 5.89597398, ..., 5.86731668, 5.77156958,
       5.78120085], shape=(1132,))

In [17]:
from sklearn.metrics import mean_absolute_error

In [18]:
mean_absolute_error(y_test,model.predict(x_test))

1.0444246590329513